apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /react
        pathType: Prefix
        backend:
          service:
            name: react-service
            port:
              number: 80
  - host: 
    http:
      paths:
      - path: /php
        pathType: Prefix
        backend:
          service:
            name: php-service
            port:
              number: 80
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:813592692089:certificate/054b52e8-6341-4e58-bd9e-9d816f9b949f
#    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'